抽出service层
codeshihaoran/shopping-store pull request #3
Opened 2023-05-29 14:41 UTC by codeshihaoran

2023-05-29 14:46 UTC, CodeDaraW requested changes

2023-05-29 14:46 UTC, CodeDaraW commented on src/service/index.js
这个里面的大部分命名都有点问题，service 意思是服务，服务应该是操作和行为，也就是这边的函数名都应该是 `doSomething`。  
例如 `homeCarousel` 是个名词而不是动词，应该是 `getHomeCarouselData`。

2023-05-29 15:20 UTC, CodeDaraW commented on src/service/index.js
还是有问题的：
1. 函数名首字母小写，遵循 `camelCase`   
2. 获取首页轮播图是 `getHomeCarouselData`，`get` 是获取这个没问题，但这只是个例子啊，不是所有的行为都是获取，例如添加购物车是 `add`

2023-05-29 15:24 UTC, codeshihaoran commented on src/service/index.js
明白了

2023-05-30 07:10 UTC, CodeDaraW commented on src/service/index.js
> +export const getHomeShoppingDate = (api, Productcategory) => axios({
typo: date 是日期，data 是数据

2023-05-30 07:11 UTC, CodeDaraW commented on src/service/index.js
> +export const getRegisterModel = (userName, password) => axios({
登陆注册也有点问题，直接叫 loginUser/registerUser 就行了，而不是 model，model 是模型的意思，user 是一种模型

2023-05-30 11:42 UTC, codeshihaoran commented on src/service/index.js
> +export const getHomeShoppingDate = (api, Productcategory) => axios({
Done

2023-05-30 11:43 UTC, codeshihaoran commented on src/service/index.js
> +export const getRegisterModel = (userName, password) => axios({
Done

2023-05-30 11:49 UTC, CodeDaraW approved these changes

2023-05-30 11:55 UTC, merged